#!/bin/bash

# Quick Command To Reset Mouse Drivers Via X11

# Example: >> mouse_save

# Device: Made for the Lenovo Legion Slim 7 Running Pop!_OS

function save_mouse_func () {
    mouse_xinput_id=$( xinput | grep Mouse | grep -o -E 'id=[0-9]+' | grep -o -E '[0-9]+' )
    touchpad_xinput_id=$( xinput | grep Touchpad | grep -o -E 'id=[0-9]+' | grep -o -E '[0-9]+' )
    
    xinput disable $mouse_xinput_id
    xinput enable $mouse_xinput_id

    xinput disable $touchpad_xinput_id
    xinput enable $touchpad_xinput_id
}

save_mouse_func
